from __future__ import annotations

import argparse
import json
from pathlib import Path

from _bootstrap import PROJECT_ROOT

BEGIN = "<!-- BEGIN AUTO-CHECKPOINT (generated by scripts/render_checkpoint.py — edit STATE.json, not this block) -->"
END = "<!-- END AUTO-CHECKPOINT -->"

# Files whose top-of-document checkpoint block is kept in sync from STATE.json.
TARGET_FILES = ("CLAUDE.md", "GOAL.md", "AGENTS.md")


def _load_active_state(root: Path) -> str | None:
    state = json.loads((root / "STATE.json").read_text(encoding="utf-8"))
    active = state.get("active_experiment")
    if not active:
        return None
    record_path = root / "experiments" / str(active) / "experiment.json"
    if not record_path.exists():
        return None
    record = json.loads(record_path.read_text(encoding="utf-8"))
    return str(record.get("state", "UNKNOWN"))


def render_block(root: Path) -> str:
    state = json.loads((root / "STATE.json").read_text(encoding="utf-8"))
    active = state.get("active_experiment", "(none)")
    record_state = _load_active_state(root) or "(no experiment.json found)"
    lb = "authorized" if state.get("leaderboard_submission_authorized") else "NOT authorized"
    lines = [
        BEGIN,
        "## Active checkpoint (single source of truth: `STATE.json`)",
        "",
        f"- **Active experiment:** `{active}`",
        f"- **Controller state (from `experiments/{active}/experiment.json`):** {record_state}",
        f"- **Phase:** {state.get('phase', '(unset)')}",
        f"- **Leaderboard submission:** {lb}",
        f"- **Summary:** {state.get('summary', '').strip()}",
        f"- **Next action:** {state.get('next_action', '').strip()}",
        "",
        f"_Generated from `STATE.json` (updated {state.get('updated_at', '?')}). "
        "Do not hand-edit this block; edit `STATE.json` and rerun `python scripts/render_checkpoint.py`. "
        "Full authorization detail lives once in `GOAL.md`._",
        END,
    ]
    return "\n".join(lines)


def apply_block(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        head = text.split(BEGIN, 1)[0]
        tail = text.split(END, 1)[1]
        return f"{head}{block}{tail}"
    # No markers yet: insert the block right after the first H1 line if present.
    stripped = text.lstrip()
    if stripped.startswith("# "):
        first_line_end = text.index("\n", text.index("# ")) + 1
        return f"{text[:first_line_end]}\n{block}\n{text[first_line_end:]}"
    return f"{block}\n\n{text}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync the active-checkpoint block from STATE.json into the governance files.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if any target file is out of sync (no writes).")
    args = parser.parse_args()

    block = render_block(PROJECT_ROOT)
    out_of_sync: list[str] = []
    for name in TARGET_FILES:
        path = PROJECT_ROOT / name
        if not path.exists():
            continue
        current = path.read_text(encoding="utf-8")
        updated = apply_block(current, block)
        if updated != current:
            out_of_sync.append(name)
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    if args.check:
        if out_of_sync:
            print("Out of sync: " + ", ".join(out_of_sync))
            return 1
        print("All governance checkpoint blocks are in sync with STATE.json.")
        return 0
    print("Updated: " + (", ".join(out_of_sync) if out_of_sync else "(all already in sync)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
